### ISSUE TITLE
Support for `datadog` gem, instead of deprecated `ddtrace` gem

### ISSUE THREAD

**Issue by tylerjc** [DataDog/datadog-lambda-rb#91]
Good afternoon all!

We're attempting to get our AWS Lambdas instrumented for the first time (with a container image using the guide found [here](https://docs.datadoghq.com/serverless/aws_lambda/installation/ruby/?tab=containerimage)).

I had originally added the two gems it calls out in that guide, but when running `bundle install` there was a note from datadog that the `ddtrace` gem is out (or on its way out), and the new thing to use is the `datadog` gem. Except that doesn't appear to be compatible with the `datadog-lambda` gem from the looks of testing things out after deploying (stacktrace snippet pasted below).

Is this known/expected with plans to add support for switching to `datadog`? Or am I missing a piece where it already is possible to use that gem instead of `ddtrace`?

Any help would be great, thanks!

## Specifications

  - Datadog Lambda ~~Layer~~ Extension version: **public.ecr.aws/datadog/lambda-extension:latest**
  - Ruby version:  **3.2.2**
  
## Stacktrace
  
  ```
2024-07-12T15:29:17.912-05:00	Error raised from handler method
2024-07-12T15:29:17.912-05:00	{
2024-07-12T15:29:17.912-05:00	"errorMessage": "unknown keyword: :span_type",
2024-07-12T15:29:17.912-05:00	"errorType": "Function<ArgumentError>",
2024-07-12T15:29:17.912-05:00	"stackTrace": [
2024-07-12T15:29:17.912-05:00	"/layers/paketo-buildpacks_bundle-install/launch-gems/ruby/3.2.0/gems/datadog-2.2.0/lib/datadog/tracing.rb:17:in `trace'",
2024-07-12T15:29:17.912-05:00	"/layers/paketo-buildpacks_bundle-install/launch-gems/ruby/3.2.0/gems/datadog-lambda-2.22.0/lib/datadog/lambda/trace/listener.rb:51:in `on_start'",
2024-07-12T15:29:17.912-05:00	"/layers/paketo-buildpacks_bundle-install/launch-gems/ruby/3.2.0/gems/datadog-lambda-2.22.0/lib/datadog/lambda.rb:64:in `wrap'",
2024-07-12T15:29:17.912-05:00	"/workspace/lambdas/transmitter.rb:13:in `process'",
  ```

**Comment by kwent** [comment]
Please update

**Comment by duncanista** [comment]
Hey sorry,

We are working on upgrading this soon.
First we'll support 3.3, then upgrade the gem on another release!

Sorry for the inconvenience, we haven't had enough bandwidth to support this, but we are now actively working on it.

**Comment by duncanista** [comment]
Working actively on this, added #99 to address some issues

**Comment by duncanista** [comment]
Still working on it, as it's not fully compatible with the new extension for some reason, need to figure out what might be the issue there!

**Comment by duncanista** [comment]
Found the issue in #100 and will start creating a release candidate which should be available as soon as the holidays end, early 2025

**Comment by duncanista** [comment]
Doing a release tomorrow
